export const TRANSCRIPT = {
  monologues: [
    {
      speaker: "Flavius",
      words: [
        "Hence!",
        "Home,",
        "you",
        "idle",
        "creatures,",
        "get",
        "you",
        "home!",
        "Is",
        "this",
        "a",
        "holiday?",
        "What,",
        "know",
        "you",
        "not,",
        "Being",
        "mechanical,",
        "you",
        "ought",
        "not",
        "walk",
        "Upon",
        "a",
        "laboring",
        "day",
        "without",
        "the",
        "sign",
        "Of",
        "your",
        "profession?",
        "Speak,",
        "what",
        "trade",
        "art",
        "thou?",
      ],
    },
    {
      speaker: "Carpenter",
      words: ["Why,", "sir,", "a", "carpenter."],
    },
    {
      speaker: "Marullus",
      words: [
        "Where",
        "is",
        "thy",
        "leather",
        "apron",
        "and",
        "thy",
        "rule?",
        "What",
        "dost",
        "thou",
        "with",
        "thy",
        "best",
        "apparel",
        "on?",
        "You,",
        "sir,",
        "what",
        "trade",
        "are",
        "you?",
      ],
    },
    {
      speaker: "Cobbler",
      words: [
        "Truly,",
        "sir,",
        "in",
        "respect",
        "of",
        "a",
        "fine",
        "workman,",
        "I",
        "am",
        "but,",
        "as",
        "you",
        "would",
        "say,",
        "a",
        "cobbler.",
      ],
    },
    {
      speaker: "Marullus",
      words: [
        "But",
        "what",
        "trade",
        "art",
        "thou?",
        "Answer",
        "me",
        "directly.",
      ],
    },
    {
      speaker: "Cobbler",
      words: [
        "A",
        "trade,",
        "sir,",
        "that",
        "I",
        "hope",
        "I",
        "may",
        "use",
        "with",
        "a",
        "safe",
        "conscience,",
        "which",
        "is",
        "indeed,",
        "sir,",
        "a",
        "mender",
        "of",
        "bad",
        "soles.",
      ],
    },
    {
      speaker: "Flavius",
      words: [
        "What",
        "trade,",
        "thou",
        "knave?",
        "Thou",
        "naughty",
        "knave,",
        "what",
        "trade?",
      ],
    },
    {
      speaker: "Cobbler",
      words: [
        "Nay,",
        "I",
        "beseech",
        "you,",
        "sir,",
        "be",
        "not",
        "out",
        "with",
        "me.",
        "Yet",
        "if",
        "you",
        "be",
        "out,",
        "sir,",
        "I",
        "can",
        "mend",
        "you.",
      ],
    },
    {
      speaker: "Marullus",
      words: [
        "What",
        "mean’st",
        "thou",
        "by",
        "that?",
        "Mend",
        "me,",
        "thou",
        "saucy",
        "fellow?",
      ],
    },
    {
      speaker: "Cobbler",
      words: ["Why,", "sir,", "cobble", "you."],
    },
    {
      speaker: "Flavius",
      words: ["Thou", "art", "a", "cobbler,", "art", "thou?"],
    },
    {
      speaker: "Cobbler",
      words: [
        "Truly,",
        "sir,",
        "all",
        "that",
        "I",
        "live",
        "by",
        "is",
        "with",
        "the",
        "awl.",
        "I",
        "meddle",
        "with",
        "no",
        "tradesman’s",
        "matters",
        "nor",
        "women’s",
        "matters,",
        "but",
        "withal",
        "I",
        "am",
        "indeed,",
        "sir,",
        "a",
        "surgeon",
        "to",
        "old",
        "shoes:",
        "when",
        "they",
        "are",
        "in",
        "great",
        "danger,",
        "I",
        "recover",
        "them.",
        "As",
        "proper",
        "men",
        "as",
        "ever",
        "trod",
        "upon",
        "neat’s",
        "leather",
        "have",
        "gone",
        "upon",
        "my",
        "handiwork.",
      ],
    },
  ],
};

export const HIGHLIGHTS = [
  {
    startMonologue: 0,
    startWord: 1,
    endMonologue: 0,
    endWord: 11,
  },
  {
    startMonologue: 0,
    startWord: 8,
    endMonologue: 1,
    endWord: 3,
  },
];
